/* Generated by SharpKit 5 v5.4.4 */

if (typeof(JsTypes) == "undefined")
    var JsTypes = [];
var Neptuo$Services$Queries$Handlers$IQueryHandler$2 = {
    fullname: "Neptuo.Services.Queries.Handlers.IQueryHandler$2",
    baseTypeName: "System.Object",
    assemblyName: "Neptuo.Services.Queries",
    Kind: "Interface",
    ctors: [],
    IsAbstract: true
};
JsTypes.push(Neptuo$Services$Queries$Handlers$IQueryHandler$2);
var Neptuo$Services$Queries$IQuery$1 = {
    fullname: "Neptuo.Services.Queries.IQuery$1",
    baseTypeName: "System.Object",
    assemblyName: "Neptuo.Services.Queries",
    Kind: "Interface",
    ctors: [],
    IsAbstract: true
};
JsTypes.push(Neptuo$Services$Queries$IQuery$1);
var Neptuo$Services$Queries$IQueryDispatcher = {
    fullname: "Neptuo.Services.Queries.IQueryDispatcher",
    baseTypeName: "System.Object",
    assemblyName: "Neptuo.Services.Queries",
    Kind: "Interface",
    ctors: [],
    IsAbstract: true
};
JsTypes.push(Neptuo$Services$Queries$IQueryDispatcher);
var Neptuo$Services$Queries$VersionInfo = {
    fullname: "Neptuo.Services.Queries.VersionInfo",
    baseTypeName: "System.Object",
    staticDefinition: {
        cctor: function (){
            Neptuo.Services.Queries.VersionInfo.Version = "0.1.0";
        },
        GetVersion: function (){
            return new System.Version.ctor$$String("0.1.0");
        }
    },
    assemblyName: "Neptuo.Services.Queries",
    Kind: "Class",
    definition: {
        ctor: function (){
            System.Object.ctor.call(this);
        }
    },
    ctors: [],
    IsAbstract: true
};
JsTypes.push(Neptuo$Services$Queries$VersionInfo);

